export type Order = {
  id: string;
  order_no: string;
  order_date: string;
  customer_name: string;
  contact: string | null;
  country: string | null;
  product_line: string | null;
  quantity: number;
  sales_amount_rmb: number;
  sales_amount_effective_rmb: number;
  order_status: string;
  payment_status: string;
  deposit_amount_rmb: number;
  payment_currency: string | null;
  rmb_payment_method: string | null;
  payment_remark: string | null;
  shipping_status: string;
  shipping_method: string | null;
  shipping_company: string | null;
  tracking_no: string | null;
  shipping_date: string | null;
  shipping_remark: string | null;
  is_refund_or_cancelled: boolean;
  remark: string | null;
  created_at: string;
  updated_at: string;
};

export type OrderItem = {
  id: string;
  order_id: string;
  product_line: string;
  quantity: number;
  sales_amount_rmb: number;
  sort_order: number;
  created_at: string;
  updated_at: string;
};

export type Customer = {
  id: string;
  customer_key: string | null;
  name: string;
  contact: string | null;
  country: string | null;
  first_order_date: string | null;
  last_order_date: string | null;
  main_product_line: string | null;
  total_orders: number;
  total_quantity: number;
  total_sales_rmb: number;
  repurchase_status: string;
  customer_value_level: string;
  repurchase_potential: string;
  days_since_last_order: number | null;
  follow_priority: string;
  follow_suggestion: string | null;
  last_follow_date: string | null;
  last_follow_result: string | null;
  next_follow_date: string | null;
  remark: string | null;
  created_at: string;
  updated_at: string;
};

export type DailyLead = {
  id: string;
  stat_date: string;
  facebook_leads: number;
  whatsapp1: number;
  whatsapp2: number;
  total_increase: number;
  total_increase_override: number | null;
  handbag_group: number;
  handbag_group_increase: number;
  handbag_group_increase_override: number | null;
  backpack_group: number;
  backpack_group_increase: number;
  backpack_group_increase_override: number | null;
  increase_note: string | null;
  is_handbag_group_reset: boolean;
  is_backpack_group_reset: boolean;
  created_at: string;
  updated_at: string;
};
